"""Configuración compartida del juego."""

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FPS = 60

PIZZA_SIZE = (32, 32)
PIZZA_INTERVAL = 1.0
PIZZA_SPEED = 900

ENEMY_INTERVAL = 3.0
MAX_ENEMIES = 8

DETECTION_RADIUS = 300
DEALER_SPEED = 450
DEALER_STARTING_LIVES = 3
DEALER_MAX_LIVES = 5
INVULNERABILITY_DURATION = 2.0
INVULNERABILITY_BLINK_INTERVAL = 0.15

HEART_SIZE = (32, 32)
HEART_GAP = 6
